# Generated by Django 4.1.6 on 2023-04-16 15:26

import My.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slug', models.SlugField(max_length=128, unique=True)),
                ('Bio', models.TextField(blank=True, max_length=128)),
                ('Photo', models.ImageField(blank=True, upload_to=My.models.user_directory_path)),
                ('Random_code_for_password', models.CharField(blank=True, max_length=16)),
                ('Photo_Thumbnail', imagekit.models.fields.ProcessedImageField(upload_to=My.models.user_thumbnail_directory_path)),
                ('HTMLCode', models.TextField(blank=True, max_length=1024)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='UserChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Users', models.ManyToManyField(to='My.additiontouser')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField()),
                ('Text', models.TextField(blank=True)),
                ('Photo', models.ImageField(blank=True, upload_to=My.models.Massage_Photo_directory_path)),
                ('File', models.FileField(blank=True, upload_to=My.models.Massage_File_directory_path)),
                ('Chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My.userchat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.AddField(
            model_name='additiontouser',
            name='AdminForChat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='My.userchat'),
        ),
        migrations.AddField(
            model_name='additiontouser',
            name='Massages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='My.massage'),
        ),
        migrations.AddField(
            model_name='additiontouser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
