# Generated by Django 4.1.6 on 2023-05-19 17:06

import My.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.SlugField(max_length=128, unique=True)),
                ('Image', models.ImageField(blank=True, upload_to=My.models.Chat_Image_directory_path)),
                ('Users', models.ManyToManyField(blank=True, null=True, related_name='Users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('Text', models.TextField(blank=True)),
                ('Photo', models.ImageField(blank=True, upload_to=My.models.Post_Photo_directory_path)),
                ('File', models.FileField(blank=True, upload_to=My.models.Post_File_directory_path)),
                ('ForUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ForUser', to=settings.AUTH_USER_MODEL)),
                ('FromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FromUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('Text', models.TextField(blank=True)),
                ('Photo', models.ImageField(blank=True, upload_to=My.models.Massage_Photo_directory_path)),
                ('File', models.FileField(blank=True, upload_to=My.models.Massage_File_directory_path)),
                ('Chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My.chat')),
                ('FromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='AdditionToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slug', models.SlugField(max_length=128, unique=True)),
                ('Bio', models.TextField(blank=True, max_length=128)),
                ('Photo', models.ImageField(blank=True, upload_to=My.models.user_directory_path)),
                ('Random_code_for_password', models.CharField(blank=True, max_length=16)),
                ('HTMLCode', models.TextField(blank=True, max_length=1024)),
                ('AdminForChat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='My.chat')),
                ('Friends', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='My.additiontouser')),
                ('Posts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='My.post')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
