# Generated by Django 4.0 on 2023-07-24 12:50

import My.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.SlugField(max_length=128, unique=True)),
                ('Image', models.ImageField(blank=True, upload_to=My.models.Chat_Image_directory_path)),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('Text', models.TextField(blank=True)),
                ('Photo', models.ImageField(blank=True, upload_to=My.models.Post_Photo_directory_path)),
                ('File', models.FileField(blank=True, upload_to=My.models.Post_File_directory_path)),
                ('ForUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ForUser', to='auth.user')),
                ('FromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FromUser', to='auth.user')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Mеssage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('Text', models.TextField(blank=True)),
                ('Photo', models.ImageField(blank=True, upload_to=My.models.Message_Photo_directory_path)),
                ('File', models.FileField(blank=True, upload_to=My.models.Message_File_directory_path)),
                ('Chat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Chat', to='My.chat')),
                ('FromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='Mеssages',
            field=models.ManyToManyField(related_name='Message', to='My.Mеssage'),
        ),
        migrations.AddField(
            model_name='chat',
            name='Users',
            field=models.ManyToManyField(related_name='Users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AdditionToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slug', models.SlugField(max_length=128, unique=True)),
                ('Bio', models.TextField(blank=True, max_length=128)),
                ('Photo', models.ImageField(blank=True, upload_to=My.models.user_directory_path)),
                ('Random_code_for_password', models.CharField(blank=True, max_length=16)),
                ('HTMLCode', models.TextField(blank=True, max_length=1024)),
                ('AdminForChat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='My.chat')),
                ('Friends', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='My.additiontouser')),
                ('Posts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='My.post')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
