# Generated by Django 4.1.6 on 2023-05-19 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('My', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='Users',
            field=models.ManyToManyField(related_name='Users', to=settings.AUTH_USER_MODEL),
        ),
    ]
