# Generated by Django 4.1.6 on 2023-04-16 15:32

import My.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('My', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additiontouser',
            name='Photo_Thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=My.models.user_thumbnail_directory_path),
        ),
    ]
