# Generated by Django 4.1.6 on 2023-04-16 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My', '0002_alter_additiontouser_photo_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additiontouser',
            name='Photo_Thumbnail',
        ),
    ]
